In [1]:
import pandas as pd

data = {'name': ['Jerry','Riah','Paul'],
        'algol': ["A","A+","B"],
        'basic': ["C","B","C+"],
        'c++': ["B+","C","C+"]
        }
df = pd.DataFrame(data)
df.set_index('name', inplace=True)
df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    C+  C+

In [2]:
df.to_csv("./files/df_sample.csv")

In [3]:
df.to_json("./files/df_sample.json")

In [4]:
df.to_excel("./files/df_sample.xlsx")

In [6]:
data1 = {'name': ['Jerry','Riah','Paul'],
        'algol': ["A","A+","B"],
        'basic': ["C","B","C+"],
        'c++': ["B+","C","C+"]
        }
data2 = {'c0': [1,2,3],
         'c1': [4,5,6],
         'c2': [7,8,9],
         'c3': [10,11,12],
         'c4': [13,14,15]}

df1 = pd.DataFrame(data1)
df1.set_index('name', inplace=True)
df1

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    C+  C+

In [7]:
df2 = pd.DataFrame(data2)
df2.set_index('c0', inplace=True)
df2

    c1  c2  c3  c4
c0
1    4   7  10  13
2    5   8  11  14
3    6   9  12  15

In [14]:
df2.columns = ['씨원','씨투','씨쓰리','씨포']
df2

    씨원  씨투  씨쓰리  씨포
c0
1    4   7   10  13
2    5   8   11  14
3    6   9   12  15

In [9]:
writer = pd.ExcelWriter("./files/df_excelwriter.xlsx")
df1.to_excel(writer, sheet_name="sheet1")
df2.to_excel(writer, sheet_name="sheet2")
writer.close()

In [10]:
df = pd.read_csv('./files/auto-mpg.csv', header=None)
df.columns = ['mpg', 'cylinders', 'displacement',
              'horsepower', 'weight', 'acceleration',
              'model year', 'origin', 'name']
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [11]:
df.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

In [12]:
df.shape

(398, 9)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [17]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model year        int64
origin            int64
name             object
dtype: object

In [ ]:
df.describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [19]:
df.describe(include='all')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
count,398.000000,398.000000,398.000000,398,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,94,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,150.0,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,NaN,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,NaN,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,NaN,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,NaN,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,NaN,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,NaN,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,NaN,5140.000000,24.800000,82.000000,3.000000,NaN

In [20]:
df.count()

mpg             398
cylinders       398
displacement    398
horsepower      398
weight          398
acceleration    398
model year      398
origin          398
name            398
dtype: int64

In [21]:
type(df.count())

pandas.core.series.Series

In [22]:
unique_values = df['origin'].value_counts()
unique_values

origin
1    249
3     79
2     70
Name: count, dtype: int64

In [23]:
type(unique_values)

pandas.core.series.Series

In [25]:
df = pd.read_csv('./files/auto-mpg.csv', header=None)
df.columns = ['mpg', 'cylinders', 'displacement',
              'horsepower', 'weight', 'acceleration',
              'model year', 'origin', 'name']

In [28]:
df['mpg'].mean(), df.mpg.mean(), df[['mpg','weight']].mean()

(np.float64(23.514572864321607),
 np.float64(23.514572864321607),
 mpg         23.514573
 weight    2970.424623
 dtype: float64)

In [30]:
df['mpg'].median()

23.0

In [31]:
df['mpg'].max()

46.6

In [33]:
df['mpg'].min()

9.0

In [35]:
df['mpg'].std()

7.815984312565782

In [41]:
df.corr(numeric_only=True)

,mpg,cylinders,displacement,weight,acceleration,model year,origin
mpg,1.000000,-0.775396,-0.804203,-0.831741,0.420289,0.579267,0.563450
cylinders,-0.775396,1.000000,0.950721,0.896017,-0.505419,-0.348746,-0.562543
displacement,-0.804203,0.950721,1.000000,0.932824,-0.543684,-0.370164,-0.609409
weight,-0.831741,0.896017,0.932824,1.000000,-0.417457,-0.306564,-0.581024
acceleration,0.420289,-0.505419,-0.543684,-0.417457,1.000000,0.288137,0.205873
model year,0.579267,-0.348746,-0.370164,-0.306564,0.288137,1.000000,0.180662
origin,0.563450,-0.562543,-0.609409,-0.581024,0.205873,0.180662,1.000000